services:
  web:
    image: nginx:alpine
    container_name: babybox
    restart: unless-stopped
    ports:
      - "8106:80"
    volumes:
      - ./website:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
    ipam:
      config:
        - subnet: 172.36.0.0/24
